# -*- coding: utf-8 -*-
"""[모듈]AudioTextTransfer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_V4pKqbEDxokCM2hWrdEXBB2ppp6ZWW
"""

# 라이브러리 설치
import os
os.system("pip install -q openai-whisper jiwer ffmpeg-python")
os.system("apt install -y ffmpeg")
os.system("pip install -U jiwer")

# 라이브러리 임포트
import whisper
import subprocess

# 오디오-텍스트 변환 클래스
class WhisperModel:
  def __init__(
      self,
      model_name: str = "medium"
  ):
    self.__model = whisper.load_model(model_name)




  def TransferAudio(
      self,
      audio_path: str
  ):
    # 오디오 형식 확인
    nameSplit = os.path.splitext(audio_path)
    if nameSplit[1] in[
        ".wav",
        ".mp3",
        ".m4a",
        ".mp4",
        ".avi",
        ".mov",
        ".mkv",
        ".flac",
        ".ogg",
        ".aac",
        ".webm"
      ]:
      pass
    elif nameSplit[1] == ".pcm":
      audio_path = self.__PcmToWav(audio_path, nameSplit[0] + ".wav")
    else:
      print("지원하지 않는 형식")
      return None

    # 텍스트로 변환
    return self.__model.transcribe(audio_path, language="ko")["text"].strip()




  def __PcmToWav(self, audio_path, new_path):
    subprocess.run([
        "ffmpeg", "-y",
        "-f", "s16le", "-ar", "16000", "-ac", "1",
        "-i", audio_path,
        new_path
    ], check=True)
    print(f"\tpcm 파일을 wav 파일로 변환.\n\t저장 경로: {new_path}")
    return new_path